FROM buildpack-deps:xenial-curl

MAINTAINER luoguohui1986@gmail.com


RUN apt-get update && \
    apt-get install -y wget && \
    apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*


RUN wget https://github.com/OmniLayer/omnicore/releases/download/v0.3.0/omnicore-0.3.0-x86_64-linux-gnu.tar.gz \
    && wget https://github.com/OmniLayer/omnicore/releases/download/v0.3.0/omnicore-0.3.0-x86_64-linux-gnu.tar.gz.asc \
    && gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 7675E31CF5719832 \
    && gpg --verify omnicore-0.3.0-x86_64-linux-gnu.tar.gz.asc omnicore-0.3.0-x86_64-linux-gnu.tar.gz \
    && tar -xzf omnicore-0.3.0-x86_64-linux-gnu.tar.gz \
    && cp -R omnicore-0.3.0/* /usr/

COPY payload/config/bitcoin.conf /root/.bitcoin/

EXPOSE 8332 8333 18332 18333


CMD ["omnicored"]